server:
  port: 0

spring:
  application:
    name: order
  h2:
    console:
      enabled: true
      path: /test_db
      settings:
        web-allow-others: true
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test_db
#    username: sa
#    password:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mysql
    username: root
    password: test
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    database: h2
#    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

logging:
  level:
    com.catalog.catalogService: DEBUG
